{{- range .Values.cron.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cash.name" $ }}-cron-{{ .name }}
  labels:
    {{- include "cash.labels" $ | nindent 4 }}
    app.kubernetes.io/component: cron
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels:
            {{- include "cash.labels" $ | nindent 12 }}
            app.kubernetes.io/component: cron
        spec:
          serviceAccountName: {{ $.Values.serviceAccount.name }}
          restartPolicy: Never
          containers:
            - name: cron
              image: {{ include "cash.image" $ }}
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              args: ["cron", {{ .arg | quote }}]
              envFrom:
                {{- include "cash.envFrom" $ | nindent 16 }}
{{- end }}
