{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "cash.name" . }}-secrets
  labels:
    {{- include "cash.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ include "cash.name" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range $envKey, $remoteKey := .Values.externalSecrets.remoteKeys }}
    - secretKey: {{ $envKey }}
      remoteRef:
        key: {{ $remoteKey }}
    {{- end }}
{{- else if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash.name" . }}-secrets
  labels:
    {{- include "cash.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretValues }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
