{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cash.name" . }}-gateway
  labels:
    {{- include "cash.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cash.name" . }}
      app.kubernetes.io/component: gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cash.name" . }}-worker
  labels:
    {{- include "cash.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cash.name" . }}
      app.kubernetes.io/component: worker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
{{- end }}
